version: '3.8'

services:
  # Python backend service
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zerodha-dashboard-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env
    networks:
      - zerodha-network
    depends_on:
      - influxdb
      - grafana

  # InfluxDB time-series database
  influxdb:
    image: influxdb:2.7
    container_name: zerodha-dashboard-influxdb
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=zerodha
      - DOCKER_INFLUXDB_INIT_BUCKET=zerodha_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - zerodha-network
    ports:
      - "8086:8086"

  # Grafana visualization
  grafana:
    image: grafana/grafana:latest
    container_name: zerodha-dashboard-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    networks:
      - zerodha-network
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:

networks:
  zerodha-network:
    driver: bridge 